-- V3__seed_historical_characters.sql
-- Seed data for historical characters

INSERT INTO historical_characters (id, name, birth_year, death_year, biography, image_url, era, nationality, created_at, updated_at) VALUES
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Mikołaj Kopernik', 1473, 1543, 'Polski astronom i matematyk, twórca heliocentrycznej teorii budowy Układu Słonecznego. Jego dzieło "De revolutionibus orbium coelestium" zrewolucjonizowało astronomię.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Miko%C5%82aj_Kopernik%2C_portret%2C_1580.jpg/220px-Miko%C5%82aj_Kopernik%2C_portret%2C_1580.jpg', 'Renesans', 'Polska', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'Maria Skłodowska-Curie', 1867, 1934, 'Polska fizyczka i chemiczka, dwukrotna laureatka Nagrody Nobla (w dziedzinie fizyki w 1903 i chemii w 1911). Pionierka badań nad promieniotwórczością.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Marie_Curie_c._1920s.jpg/220px-Marie_Curie_c._1920s.jpg', 'XIX wiek', 'Polska/Francja', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('c0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'Józef Piłsudski', 1867, 1935, 'Polski polityk i wojskowy, pierwszy Marszałek Polski. Jeden z najważniejszych twórców niepodległej Polski w XX wieku.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/J%C3%B3zef_Pi%C5%82sudski_F1.jpg/220px-J%C3%B3zef_Pi%C5%82sudski_F1.jpg', 'XX wiek', 'Polska', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('d0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14', 'Jan Henryk Dąbrowski', 1755, 1818, 'Polski generał, bohater walk o niepodległość. Twórca Legionów Polskich we Włoszech, autor pieśni "Warszawianka".', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Jan_Henryk_D%C4%85browski.PNG/220px-Jan_Henryk_D%C4%85browski.PNG', 'XVIII wiek', 'Polska', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('e0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15', 'Fryderyk Chopin', 1810, 1849, 'Polski kompozytor i virtuoz fortepianu. Jeden z najwybitniejszych twórców muzyki romantycznej, nazywany "poetą fortepianu".', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Frederic_Chopin_photo.jpeg/220px-Frederic_Chopin_photo.jpeg', 'XIX wiek', 'Polska', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('f0eebc99-9c0b-4ef8-bb6d-6bb9bd380a16', 'Władysław Jagiełło', 1348, 1434, 'Wielki książę litewski i król Polski. Władca zjednoczonej Polski-Litwy, zwycięzca w bitwie pod Grunwaldem.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/W%C5%82adys%C5%82aw_Jagie%C5%82%C5%82o.PNG/220px-W%C5%82adys%C5%82aw_Jagie%C5%82%C5%82o.PNG', 'Średniowiecze', 'Polska', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
